app = "betcerta"
primary_region = "gru"

[build]
  [build.args]
    VITE_SUPABASE_URL = ""
    VITE_SUPABASE_ANON_KEY = ""

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[vm]
  memory = "1024mb"
  cpu_kind = "shared"
  cpus = 1
